#!/bin/bash

PROJECT_NAME="$1"
arrIN=(${PROJECT_NAME//\// })
LIB_NAME=${arrIN[1]}

app_path=$0
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

cd $PROJECT_NAME && cargo +nightly build -Z unstable-options --target-dir $APP_HOME/.build/$PROJECT_NAME --out-dir $APP_HOME/.build/bin
if [[ $PROJECT_NAME = java* ]]
then
  cd "$APP_HOME/$PROJECT_NAME/" && javac Main.java
  cd "$APP_HOME/$PROJECT_NAME/" && LD_LIBRARY_PATH=$APP_HOME/.build/bin java Main
fi
if [[ $PROJECT_NAME = cpp* ]]
then
  gcc -g "$APP_HOME/$PROJECT_NAME/src/main.cpp" -o "$APP_HOME/$PROJECT_NAME/main.app" "-l$LIB_NAME" "-L$APP_HOME/.build/bin"
  cd "$APP_HOME/$PROJECT_NAME/" && LD_LIBRARY_PATH=$APP_HOME/.build/bin $APP_HOME/$PROJECT_NAME/main.app
fi